[[permission]]
identifier = "allow-process-audio-file"
description = "Allows invoking the process_audio_file command"
commands.allow = ["process_audio_file"] 
[[permission]]
identifier = "allow-get-system-fonts"
description = "Allows invoking the get_system_fonts command"
commands.allow = ["get_system_fonts"] 
[[permission]]
identifier = "allow-get-font-data"
description = "Allows invoking the get_font_data command"
commands.allow = ["get_font_data"] 
[[permission]]
identifier = "allow-prepare-audio-file"
description = "Allows invoking the prepare_audio_file command"
commands.allow = ["prepare_audio_file"] 

[[permission]]
identifier = "allow-cleanup-cached-file"
description = "Allows invoking the cleanup_cached_file command"
commands.allow = ["cleanup_cached_file"]

[[permission]]
identifier = "allow-scan-music-folder"
description = "Allows invoking the scan_music_folder command"
commands.allow = ["scan_music_folder"]
